### ISSUE TITLE
GitHub Intergration

### ISSUE THREAD

**Issue by RowdyChildren** [CodeForCharlotte/codeforcharlotte.org#105]
_From @RowdyChildren on July 4, 2015 15:30_

We need to find some way to intergrate a GitHub signup, this may be somthing we need to pull the Code for Philly people in to help with

_Copied from original issue: CodeForCharlotte/laddrdocs#13_

**Comment by Jillzey** [comment]
How is this different from issue #132?

**Comment by RowdyChildren** [comment]
It isn't. closing/merging
