### ISSUE TITLE
Leadership Page Sidebar

### ISSUE THREAD

**Issue by RowdyChildren** [CodeForCharlotte/codeforcharlotte.org#106]
Change side bar to open leadership positions.  Text to follow

**Comment by Jillzey** [comment]
Text for this page is here: https://docs.google.com/document/d/1xFZZKNMIQMoM9vc7YKZhnRr6oPYP01iCter-aZrQ3pI/edit

**Comment by RowdyChildren** [comment]
@jillzey: Any content here yet?
