### ISSUE TITLE
Fix the sidebars

### ISSUE THREAD

**Issue by RowdyChildren** [CodeForCharlotte/codeforcharlotte.org#108]
_From @RowdyChildren on July 4, 2015 14:52_

The side bars all have "Headers" but a lot of them are Lorem Ipsum or Kafka's Story of "The Metamorphosis"

_Copied from original issue: CodeForCharlotte/laddrdocs#10_

**Comment by Jillzey** [comment]
I'm going to close this because I'm going to get much more specific with where content is and needs to be. :)
