### ISSUE TITLE
Events Menu

### ISSUE THREAD

**Issue by RowdyChildren** [CodeForCharlotte/codeforcharlotte.org#110]
_From @RowdyChildren on July 4, 2015 14:40_

How do we want to keep the events menu up to date? We need to add content OR delete some of the events.

_Copied from original issue: CodeForCharlotte/laddrdocs#7_

**Comment by Jillzey** [comment]
I want a single page for each event.  It will be a draw for sponsors and allow us to customize the prospectus for each.  It is important. That is why I put it on there.  Once we have this set up and not all the initial work needs to be done, I will update and rotate them.
