### ISSUE TITLE
Our Road Map Main Content

### ISSUE THREAD

**Issue by RowdyChildren** [CodeForCharlotte/codeforcharlotte.org#111]
On this page:
http://stagingcfc.rileychilds.net/road-map

**Comment by Jillzey** [comment]
This is the Strategic Plan that has to be submitted to CFA each year.  Here is the link to it: https://docs.google.com/document/d/1aJoh7Zp8tEATrw5ZoN2a7SiQHQUJMoIB-5VNaymrv68/edit?usp=sharing

It just need to be put on the page with some HTML love so it is readable.

**Comment by RowdyChildren** [comment]
Converted to Markdown and added to Page
