### ISSUE TITLE
Partner Page Main Section

### ISSUE THREAD

**Issue by kpmaio** [CodeForCharlotte/codeforcharlotte.org#123]
Partner Information
Knight Foundation

Knight Foundation invests in community success by supporting civic innovation, founded on robust civic engagement, in talent, opportunity and place.

Code For Charlotte furthers not only the Knight Foundation mission of direct civic engagement, but also through its emphasis on open data, a new opportunity to engage for many more citizens.
Knight School of Communication, Queens University

The mission of the James L. Knight School of Communication is to prepare consumers and creators of communication messages to become engaged citizens, advocates and leaders in the communities they serve. In our academic programs and our community initiatives, we are discovering how universities can shape their local media ecosystems.

Dean Eric Freedman has welcomed us to his lab in the name of citizen engagement and many other items. Be sure to check out Digital Charlotte.
Logical Advantage

Logical Advantage provides a variety of solutions to support business IT, including Application Outsourcing, IT Consulting and IT Staffing.

LA is a proud supporter of Code for Charlotte. Not only for its purpose, but to also advance the visibility of the technology committee within the great Charlotte area.

**Comment by Jillzey** [comment]
Changing partners to have text for City and logos for more one time partners.

**Comment by Jillzey** [comment]
Adding text about how to become a parter with link to prospectus
