### ISSUE TITLE
Partners Page Sidebar

### ISSUE THREAD

**Issue by kpmaio** [CodeForCharlotte/codeforcharlotte.org#124]
Put information in sidebar on Partner page on how to become a partner.

**Comment by Jillzey** [comment]
Help us further our work by becoming a Code for Charlotte Partner.  We have many different ways to become a partner and would love to talk to you about it.  Please email Jill for further information. In the meantime, check out our Sponsorship Prospectus. 

Email link: jbjers@codeforamerica.org
Sponsorship Prospectus will also be a link when the prospectus is completed.
