### ISSUE TITLE
Media Page Sidebar Addition

### ISSUE THREAD

**Issue by Jillzey** [CodeForCharlotte/codeforcharlotte.org#133]
On Page: http://stagingcfc.rileychilds.net/media

Content is updated, mostly

**Comment by Jillzey** [comment]
Needs a sidebar added to the left side for a link to the press kit. The text for that is here: 

Contact Us!
Looking to write an article about Code for Charlotte? Contact Jill Bjers [link to email address jbjers@codeforamerica.org] and/or Jim Van Fleet [link to email address jvanfleet@codeforamerica.org]. 

To view our press kit, click here [link to press kit page at codeforcharlotte.org/press-kit].

**Comment by RowdyChildren** [comment]
@Jillzey is this in addition to the "Press Inquires?" content block
