### ISSUE TITLE
Project Updates functionality, error message

### ISSUE THREAD

**Issue by Jillzey** [CodeForCharlotte/codeforcharlotte.org#137]
When selecting the "log buzz" button inside a project. This is the error:

Fatal error: Class 'Laddr\ProjectBuzzRequestHandler' not found in /emergence/sites/cfcstaging/data/301 on line 3

Tested on the Charlotte Local Wiki project.

**Comment by RowdyChildren** [comment]
This issue is related to something going on with the core Laddr implementation. I will get with Chris tomorrow to resolve this!

**Comment by RowdyChildren** [comment]
Overwrote the Buzz feature, file was deleted and now it works
