### ISSUE TITLE
Create Events Pages

### ISSUE THREAD

**Issue by Jillzey** [CodeForCharlotte/codeforcharlotte.org#152]
For whatever frustrate Jill reason, creating the events pages wouldn't work like normal.  What we need are pages nested in the events section. Here is a list of the pages:
staging.codeforcharlotte.com/events/hack-night
staging.codeforcharlotte.com/events/birthday-party
staging.codeforcharlotte.com/events/codeacross
staging.codeforcharlotte.com/events/ndoch
staging.codeforcharlotte.com/events/summer-party
staging.codeforcharlotte.com/events/city-camp
staging.codeforcharlotte.com/events/winter-party

I don't have a format for the page yet, Just need the pages created correctly.

**Comment by RowdyChildren** [comment]
@Jillzey, the issue may be that those pages were created and then deleted. Allow me to restore them, please standby

**Comment by RowdyChildren** [comment]
@Jillzey you cannot have a page and a directory names the same thing, I am going to ping Chris and see if he can offer some insight. For now create event templates in the /html-templates/event directory and controllers in the /site-root/event directory.
Over and out
./r
