### ISSUE TITLE
page not found

### ISSUE THREAD

**Issue by vanderh0ff** [CodeForCharlotte/codeforcharlotte.org#160]
the (focus areas link)[http://www.codeforcharlotte.org/focus-areas]  on the (get involved)[http://www.codeforcharlotte.org/get-involved] page 404's

**Comment by RowdyChildren** [comment]
Thanks, I will take a look

—
Sent from Mailbox by Riley Childs
https://rileychilds.me

**Comment by RowdyChildren** [comment]
issue confirmed

**Comment by bitflipper1** [comment]
Fixed.  Goes to Road Maps now on staging site

**Comment by RowdyChildren** [comment]
confirming before content push

**Comment by RowdyChildren** [comment]
change approved, qa complete, content pushed

**Comment by RowdyChildren** [comment]
@bitflipper1 thanks for the help!
