### ISSUE TITLE
Updated leadership page template

### ISSUE THREAD

**Issue by AndrewNatoli** [CodeForCharlotte/codeforcharlotte.org#162]
Revised /templates/team/leadership.tpl 

Photos now stay circular and scale for different window sizes.

**Comment by RowdyChildren** [comment]
I will take a look and push the change

**Comment by RowdyChildren** [comment]
@AndrewNatoli they seem a bit big when I change my chrome window size, is this expected

**Comment by AndrewNatoli** [comment]
@RowdyChildren What size are you changing to (Phone, Tablet, Desktop, Super high desktop resolution)? 

On tablets they can be a little large as they fall under the left sidebar and the container takes up the full width. On mobile they collapse to one per row so a single image will take up the full width.

**Comment by RowdyChildren** [comment]
yes, I see what you mean. It looks pretty shitty when there is one small
image per row.
Change has been pushed.

**Comment by RowdyChildren** [comment]
Changed pushed and approved, change is now in production

**Comment by AndrewNatoli** [comment]
So... it's fine as-is then as it's one full-width image per row? Or should I look into getting two per row on mobile?

**Comment by RowdyChildren** [comment]
yeah, it is fine. There is one size in which the images are huge and super pixelly, but the likely hood of that exact really strange window size occurring is not high...so don't worry about it
