### ISSUE TITLE
Add Partners Page

### ISSUE THREAD

**Issue by Jillzey** [CodeForCharlotte/codeforcharlotte.org#93]
Add a page for partners to list municipal partners.

**Comment by scottelundgren** [comment]
Will partner's edit the page (i.e.: submit pull requests) ?
Does this partners & municipal partners mapping already exist and you just need the page created?

**Comment by Jillzey** [comment]
Sorry for the confusion about this. I thought the issue would apply to laddr because I didn't realize that Laddr wasn't being set up in Github. I don't know how it works to understand if Laddr will let us work in Github. Any help clarifying that would be great.

**Comment by scottelundgren** [comment]
Depends on: #96

**Comment by Jillzey** [comment]
Tomorrow I will bring my printed wire frame and notes on the website
structure, if you are interested in seeing it.  I've been pulling my
favorite stuff off of other brigade websites to use with ours.

Here is the CNAME stuff I sent to the city:









*Give authoritative control over the zone emergence.codeforcharlotte.org
<http://emergence.codeforcharlotte.org/> tons1.digitalocean.com
<http://ns1.digitalocean.com/>ns2.digitalocean.com
<http://ns2.digitalocean.com/>ns3.digitalocean.com
<http://ns3.digitalocean.com/>create CNAME records for the
following:production.codeforcharlotte.org
<http://production.codeforcharlotte.org/> -> emergence.codeforcharlotte.org
<http://emergence.codeforcharlotte.org/>staging.codeforcharlotte.org
<http://staging.codeforcharlotte.org/> -> emergence.codeforcharlotte.org
<http://emergence.codeforcharlotte.org/>laddr.codeforcharlotte.org
<http://laddr.codeforcharlotte.org/> -> emergence.codeforcharlotte.org
<http://emergence.codeforcharlotte.org/>*

I still haven't heard from them. I'm going to bring up the idea of getting
the domain from the city. I would rather have control of our own stuff.

Have a wonderful day!

Jill Bjers
Co-Captain | Code for Charlotte | @codeforclt

Want to schedule a meeting with me? Do it HERE
<https://jillbjers.youcanbook.me/>!



On Tue, Jan 20, 2015 at 12:22 PM, Scott E Lundgren <notifications@github.com
