### ISSUE TITLE
Request a DNS entry for the staging server from the City of Charlotte

### ISSUE THREAD

**Issue by scottelundgren** [CodeForCharlotte/codeforcharlotte.org#97]
With the host/infrastructure set up we need to ask the city for a DNS entry so that 

something.codeforcharlotte.org

points to the IP address of the server that was set up to satisfy #94

**Comment by bigfleet** [comment]
Can't set cname records for apex, has to be A

Cheers,

Jim

**Comment by scottelundgren** [comment]
Noted. I was going to fast using the words that @Jillzey sent to capture as issues/actions what she and @RowdyChildren got done on Saturday

**Comment by Jillzey** [comment]
This was the request sent to the city on Monday morning. I haven't heard from anyone. I emailed it to both Twyla and Shawn:
Give authoritative control over the zone emergence.codeforcharlotte.org to
ns1.digitalocean.com
ns2.digitalocean.com
ns3.digitalocean.com

create CNAME records for the following:
production.codeforcharlotte.org -> emergence.codeforcharlotte.org
staging.codeforcharlotte.org -> emergence.codeforcharlotte.org
laddr.codeforcharlotte.org -> emergence.codeforcharlotte.org


I would like to see what everyone else thinks about possibly requesting to take over our domain. I know the pro of having the city own it is they pay for it but I personally think it is worth paying for to have ease of use with it.  Response is usually slow.

**Comment by RowdyChildren** [comment]
We may want to also consider requesting that authoritative control for the entire codeforcharlotte.org zone be granted to CloudFlare or another DNS provider.

**Comment by RowdyChildren** [comment]
we can control the DNS and they will pay for it, or (I think this would be best) request that they transfer the domain to us and we would pay the $15/year for renewal.
