### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by maxmeyer** [CodeForCharlotte/codeforcharlotte.org#99]
Would you mind to add a license to your project, e.g. MIT for code and CC for content?

**Comment by bigfleet** [comment]
Not at all!  I'm familiar with the LICENSE mechanism for code-- can you inform me of the process for content?

**Comment by scottelundgren** [comment]
this is a great question because we're in the midst of transferring the site from being built on middleman to the laddr.io project used by @CfABrigadePhiladelphia. I'm not sure anyone has looked at how to keep a repo for the new site with an MIT license for code and CC for content.

**Comment by maxmeyer** [comment]
Mmmh... No, I'm not a specialist for that :smile:. While not add both licenses to the repo and explain it in the readme. 

I'm more interested in using some helper code in your `config.rb`, but without a proper license, this is difficult to send "upstream".

**Comment by scottelundgren** [comment]
Is it the link_to helper you're after? It came from [Middleman's Issue 303](https://github.com/middleman/middleman/issues/303#issuecomment-14026823) and I posted about it in the [Middleman Forum](https://forum.middlemanapp.com/t/how-to-set-bootstrap-active-class/1220/4) so you have other sources to cite ;)

**Comment by maxmeyer** [comment]
> Is it the link_to helper you're after?

Correct. :) I would like to create a PR to publish it on `middleman-guides`.
